[package]
name = "TerraLocalis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.0"
rand = "0.8.3"
glam = "0.17.3"
